package users;

public enum ManagerType {
	OFFICE_REGISTRATOR,
    DEAN_OFFICE,
    ALUMNI_OFFICE,
    IT_SERVICES,
    DEPARTMENT_OF_YOUTH_POLICY,
    CAREER_SERVICES_OFFICE,
    INTERNATIONAL_OFFICE
}
